import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // Create crystals based on your actual inventory - ALL 21 CRYSTALS
  const crystals = [
    {
      name: 'Tiger Eye Bracelet',
      slug: 'tiger-eye-bracelet',
      description: 'Powerful Tiger Eye bracelet for courage, confidence, and protection. Known as the stone of courage and personal power.',
      price: 34.99,
      category: 'Protection',
      chakra: 'Solar Plexus',
      element: 'Fire',
      hardness: '7',
      origin: 'South Africa',
      rarity: 'Common',
      image: '/images/crystals/TIGER_EYE/TG1.png',
      images: JSON.stringify(['/images/crystals/TIGER_EYE/TG1.png', '/images/crystals/TIGER_EYE/TG2.png', '/images/crystals/TIGER_EYE/TG3.png', '/images/crystals/TIGER_EYE/TG4.png']),
      properties: JSON.stringify(['Courage', 'Confidence', 'Protection', 'Grounding']),
      colors: JSON.stringify(['Golden Brown', 'Yellow', 'Brown']),
      zodiacSigns: JSON.stringify(['Leo', 'Capricorn']),
      birthMonths: JSON.stringify([8, 12]),
      keywords: JSON.stringify(['courage', 'confidence', 'protection']),
      stockQuantity: 15,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: true,
    },
    {
      name: 'Aquamarine Bracelet',
      slug: 'aquamarine-bracelet',
      description: 'Serene blue Aquamarine bracelet for clarity, communication, and emotional balance. The stone of courage and serenity.',
      price: 39.99,
      category: 'Communication',
      chakra: 'Throat',
      element: 'Water',
      hardness: '7.5',
      origin: 'Brazil',
      rarity: 'Uncommon',
      image: '/images/crystals/AQUAMARINE/AQ1.png',
      images: JSON.stringify(['/images/crystals/AQUAMARINE/AQ1.png', '/images/crystals/AQUAMARINE/AQ2.png', '/images/crystals/AQUAMARINE/AQ3.png', '/images/crystals/AQUAMARINE/AQ4.png']),
      properties: JSON.stringify(['Clarity', 'Communication', 'Courage', 'Serenity']),
      colors: JSON.stringify(['Light Blue', 'Sea Blue', 'Pale Blue']),
      zodiacSigns: JSON.stringify(['Pisces', 'Aquarius', 'Gemini']),
      birthMonths: JSON.stringify([3, 11]),
      keywords: JSON.stringify(['clarity', 'communication', 'serenity']),
      stockQuantity: 12,
      lowStockThreshold: 3,
      isActive: true,
      isFeatured: true,
    },
    {
      name: 'Citrine Bracelet',
      slug: 'citrine-bracelet',
      description: 'Bright golden Citrine bracelet for abundance, manifestation, and joy. Known as the "Merchant\'s Stone" for attracting wealth.',
      price: 44.99,
      category: 'Abundance',
      chakra: 'Solar Plexus',
      element: 'Fire',
      hardness: '7',
      origin: 'Brazil',
      rarity: 'Uncommon',
      image: '/images/crystals/CITRINE/CI1.png',
      images: JSON.stringify(['/images/crystals/CITRINE/CI1.png', '/images/crystals/CITRINE/CI2.png', '/images/crystals/CITRINE/CI3.png', '/images/crystals/CITRINE/CI4.png']),
      properties: JSON.stringify(['Abundance', 'Manifestation', 'Joy', 'Confidence']),
      colors: JSON.stringify(['Golden Yellow', 'Amber', 'Light Yellow']),
      zodiacSigns: JSON.stringify(['Gemini', 'Aries', 'Leo']),
      birthMonths: JSON.stringify([11, 3]),
      keywords: JSON.stringify(['abundance', 'wealth', 'manifestation']),
      stockQuantity: 8,
      lowStockThreshold: 2,
      isActive: true,
      isFeatured: true,
    },
    {
      name: 'Green Jade Bracelet',
      slug: 'green-jade-bracelet',
      description: 'Beautiful Green Jade bracelet for prosperity, harmony, and good fortune. The stone of eternal youth and wisdom.',
      price: 49.99,
      category: 'Prosperity',
      chakra: 'Heart',
      element: 'Earth',
      hardness: '6.5',
      origin: 'Myanmar',
      rarity: 'Uncommon',
      image: '/images/crystals/GREEN_JADE/GJ1.png',
      images: JSON.stringify(['/images/crystals/GREEN_JADE/GJ1.png', '/images/crystals/GREEN_JADE/GJ2.png']),
      properties: JSON.stringify(['Prosperity', 'Harmony', 'Good Fortune', 'Wisdom']),
      colors: JSON.stringify(['Green', 'Emerald Green']),
      zodiacSigns: JSON.stringify(['Taurus', 'Libra', 'Virgo']),
      birthMonths: JSON.stringify([5, 9]),
      keywords: JSON.stringify(['prosperity', 'harmony', 'fortune']),
      stockQuantity: 6,
      lowStockThreshold: 2,
      isActive: true,
      isFeatured: true,
    },
    {
      name: 'Turquoise Bracelet',
      slug: 'turquoise-bracelet',
      description: 'Sacred Turquoise bracelet for protection, healing, and spiritual connection. A stone of ancient wisdom and truth.',
      price: 54.99,
      category: 'Spiritual',
      chakra: 'Throat',
      element: 'Earth',
      hardness: '6',
      origin: 'Arizona',
      rarity: 'Rare',
      image: '/images/crystals/TURQUOISE/TU1.png',
      images: JSON.stringify(['/images/crystals/TURQUOISE/TU1.png', '/images/crystals/TURQUOISE/TU2.png', '/images/crystals/TURQUOISE/TU3.png', '/images/crystals/TURQUOISE/TU4.png', '/images/crystals/TURQUOISE/TU5.png']),
      properties: JSON.stringify(['Protection', 'Healing', 'Truth', 'Wisdom']),
      colors: JSON.stringify(['Turquoise Blue', 'Sky Blue', 'Blue-Green']),
      zodiacSigns: JSON.stringify(['Sagittarius', 'Pisces', 'Scorpio']),
      birthMonths: JSON.stringify([12, 3]),
      keywords: JSON.stringify(['protection', 'truth', 'wisdom']),
      stockQuantity: 4,
      lowStockThreshold: 1,
      isActive: true,
      isFeatured: true,
    },
    {
      name: 'Rhodochrosite Bracelet',
      slug: 'rhodochrosite-bracelet',
      description: 'Beautiful pink Rhodochrosite bracelet for love, compassion, and emotional healing. The stone of the compassionate heart.',
      price: 59.99,
      category: 'Love',
      chakra: 'Heart',
      element: 'Fire',
      hardness: '4',
      origin: 'Argentina',
      rarity: 'Rare',
      image: '/images/crystals/RHODOCHROSITE/RW1.png',
      images: JSON.stringify(['/images/crystals/RHODOCHROSITE/RW1.png', '/images/crystals/RHODOCHROSITE/RW2.png', '/images/crystals/RHODOCHROSITE/RW3.png', '/images/crystals/RHODOCHROSITE/RW4.png', '/images/crystals/RHODOCHROSITE/RW5.png']),
      properties: JSON.stringify(['Love', 'Compassion', 'Emotional Healing', 'Self-Love']),
      colors: JSON.stringify(['Pink', 'Rose Pink', 'Deep Pink']),
      zodiacSigns: JSON.stringify(['Leo', 'Scorpio']),
      birthMonths: JSON.stringify([8, 10]),
      keywords: JSON.stringify(['love', 'compassion', 'healing']),
      stockQuantity: 3,
      lowStockThreshold: 1,
      isActive: true,
      isFeatured: true,
    },
    {
      name: 'Howlite Bracelet',
      slug: 'howlite-bracelet',
      description: 'Calming white Howlite bracelet for peace, patience, and stress relief. Perfect for meditation and sleep.',
      price: 29.99,
      category: 'Calming',
      chakra: 'Crown',
      element: 'Air',
      hardness: '3.5',
      origin: 'Canada',
      rarity: 'Common',
      image: '/images/crystals/HOWLITE/HW2.png',
      images: JSON.stringify(['/images/crystals/HOWLITE/HW2.png', '/images/crystals/HOWLITE/HW3.png', '/images/crystals/HOWLITE/HW4.png']),
      properties: JSON.stringify(['Calming', 'Patience', 'Stress Relief', 'Sleep']),
      colors: JSON.stringify(['White', 'Cream', 'Gray']),
      zodiacSigns: JSON.stringify(['Gemini', 'Virgo']),
      birthMonths: JSON.stringify([5, 8]),
      keywords: JSON.stringify(['calm', 'peace', 'sleep']),
      stockQuantity: 10,
      lowStockThreshold: 3,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Tree Agate Bracelet',
      slug: 'tree-agate-bracelet',
      description: 'Grounding Tree Agate bracelet for stability, growth, and connection to nature. Promotes inner peace and strength.',
      price: 34.99,
      category: 'Grounding',
      chakra: 'Root',
      element: 'Earth',
      hardness: '7',
      origin: 'India',
      rarity: 'Common',
      image: '/images/crystals/TREE_AGATE/TG1.png',
      images: JSON.stringify(['/images/crystals/TREE_AGATE/TG1.png', '/images/crystals/TREE_AGATE/TG2.png', '/images/crystals/TREE_AGATE/TG3.png', '/images/crystals/TREE_AGATE/TG4.png']),
      properties: JSON.stringify(['Grounding', 'Stability', 'Growth', 'Inner Peace']),
      colors: JSON.stringify(['White', 'Green', 'Moss Green']),
      zodiacSigns: JSON.stringify(['Virgo', 'Gemini']),
      birthMonths: JSON.stringify([8, 5]),
      keywords: JSON.stringify(['grounding', 'stability', 'nature']),
      stockQuantity: 7,
      lowStockThreshold: 2,
      isActive: true,
      isFeatured: false,
    },
    // ADDITIONAL CRYSTALS TO REACH 21 TOTAL
    {
      name: 'Money Magnet Bracelet',
      slug: 'money-magnet-bracelet',
      description: 'A powerful combination of abundance stones designed to attract wealth and prosperity. Features Citrine, Pyrite, and Green Aventurine.',
      price: 42.00,
      category: 'Abundance',
      chakra: 'Solar Plexus',
      element: 'Fire',
      hardness: '6-7',
      origin: 'Brazil, India, Peru',
      rarity: 'Uncommon',
      image: '/images/MONEY MAGNET/MM1.png',
      images: JSON.stringify(['/images/MONEY MAGNET/MM1.png', '/images/MONEY MAGNET/MM2.png', '/images/MONEY MAGNET/MM3.png', '/images/MONEY MAGNET/MM4.png']),
      properties: JSON.stringify(['Wealth Attraction', 'Prosperity', 'Abundance', 'Success']),
      colors: JSON.stringify(['Golden', 'Green', 'Yellow']),
      zodiacSigns: JSON.stringify(['Leo', 'Aries', 'Sagittarius']),
      birthMonths: JSON.stringify([3, 4, 7, 8, 11, 12]),
      keywords: JSON.stringify(['wealth', 'prosperity', 'abundance']),
      stockQuantity: 25,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: true,
    },
    {
      name: 'Triple Protection Bracelet',
      slug: 'triple-protection-bracelet',
      description: 'A powerful combination of Tiger Eye, Black Obsidian & Hematite for ultimate protection against negative energies.',
      price: 35.00,
      category: 'Protection',
      chakra: 'Root',
      element: 'Earth',
      hardness: '6-7',
      origin: 'South Africa, Mexico, Brazil',
      rarity: 'Common',
      image: '/images/TRIPLE PROTECTION /TP1.png',
      images: JSON.stringify(['/images/TRIPLE PROTECTION /TP1.png', '/images/TRIPLE PROTECTION /TP2.png', '/images/TRIPLE PROTECTION /TP3.png', '/images/TRIPLE PROTECTION /TP4.png']),
      properties: JSON.stringify(['Protection', 'Grounding', 'Courage', 'Stability']),
      colors: JSON.stringify(['Golden', 'Black', 'Metallic Gray']),
      zodiacSigns: JSON.stringify(['Leo', 'Capricorn', 'Aries']),
      birthMonths: JSON.stringify([1, 7, 8, 12]),
      keywords: JSON.stringify(['protection', 'grounding', 'courage']),
      stockQuantity: 15,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: true,
    },
    {
      name: 'Lava 7 Chakra Bracelet',
      slug: 'lava-7-chakra-bracelet',
      description: 'Balance all seven chakras with this beautiful lava stone bracelet featuring genuine chakra stones.',
      price: 28.00,
      category: 'Chakra Healing',
      chakra: 'All Chakras',
      element: 'Fire',
      hardness: '5-6',
      origin: 'Hawaii, Iceland, Italy',
      rarity: 'Common',
      image: '/images/crystals/7 CHAKRA/LV1.png',
      images: JSON.stringify(['/images/crystals/7 CHAKRA/LV1.png', '/images/crystals/7 CHAKRA/LV2.png', '/images/crystals/7 CHAKRA/LV3.png', '/images/crystals/7 CHAKRA/LV4.png']),
      properties: JSON.stringify(['Chakra Balancing', 'Grounding', 'Essential Oil Diffuser']),
      colors: JSON.stringify(['Black', 'Multi-colored']),
      zodiacSigns: JSON.stringify(['All Signs']),
      birthMonths: JSON.stringify([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
      keywords: JSON.stringify(['chakra', 'balance', 'grounding']),
      stockQuantity: 20,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: true,
    },
    {
      name: 'Rose Amethyst Clear Quartz Bracelet',
      slug: 'rose-amethyst-clear-quartz-bracelet',
      description: 'A harmonious blend of love, spirituality, and clarity. This combination promotes emotional healing and spiritual growth.',
      price: 42.00,
      category: 'Love',
      chakra: 'Heart',
      element: 'Water',
      hardness: '7',
      origin: 'Brazil, Madagascar, USA',
      rarity: 'Uncommon',
      image: '/images/ROSE AMETHYST CLEAR/RA1.png',
      images: JSON.stringify(['/images/ROSE AMETHYST CLEAR/RA1.png', '/images/ROSE AMETHYST CLEAR/RA2.png', '/images/ROSE AMETHYST CLEAR/RA3.png', '/images/ROSE AMETHYST CLEAR/RA4.png']),
      properties: JSON.stringify(['Love', 'Spiritual Growth', 'Clarity', 'Emotional Healing']),
      colors: JSON.stringify(['Pink', 'Purple', 'Clear']),
      zodiacSigns: JSON.stringify(['Taurus', 'Cancer', 'Pisces']),
      birthMonths: JSON.stringify([2, 4, 5, 6, 7]),
      keywords: JSON.stringify(['love', 'healing', 'clarity']),
      stockQuantity: 18,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Blue Apatite Bracelet',
      slug: 'blue-apatite-bracelet',
      description: 'A stone of manifestation and communication. Blue Apatite enhances psychic abilities and promotes clear communication.',
      price: 44.00,
      category: 'Communication',
      chakra: 'Throat',
      element: 'Water',
      hardness: '5',
      origin: 'Madagascar, Brazil, Mexico',
      rarity: 'Uncommon',
      image: '/images/crystals/BLUE APATITE/BA1.png',
      images: JSON.stringify(['/images/crystals/BLUE APATITE/BA1.png', '/images/crystals/BLUE APATITE/BA2.png', '/images/crystals/BLUE APATITE/BA3.png', '/images/crystals/BLUE APATITE/BA4.png']),
      properties: JSON.stringify(['Manifestation', 'Communication', 'Psychic Abilities', 'Goal Achievement']),
      colors: JSON.stringify(['Blue', 'Deep Blue', 'Light Blue']),
      zodiacSigns: JSON.stringify(['Gemini', 'Pisces']),
      birthMonths: JSON.stringify([2, 3, 5, 6]),
      keywords: JSON.stringify(['manifestation', 'communication', 'psychic']),
      stockQuantity: 14,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Dalmatian Jasper Bracelet',
      slug: 'dalmatian-jasper-bracelet',
      description: 'A playful stone that brings joy and positivity. Dalmatian Jasper helps overcome depression and brings out your inner child.',
      price: 26.00,
      category: 'Emotional Healing',
      chakra: 'Root',
      element: 'Earth',
      hardness: '6.5-7',
      origin: 'Mexico, India',
      rarity: 'Common',
      image: '/images/crystals/DALMATIAN/DM1.png',
      images: JSON.stringify(['/images/crystals/DALMATIAN/DM1.png', '/images/crystals/DALMATIAN/DM2.png', '/images/crystals/DALMATIAN/DM3.png', '/images/crystals/DALMATIAN/DM4.png']),
      properties: JSON.stringify(['Joy', 'Positivity', 'Friendship', 'Loyalty', 'Inner Child']),
      colors: JSON.stringify(['White', 'Black', 'Cream']),
      zodiacSigns: JSON.stringify(['Gemini', 'Virgo']),
      birthMonths: JSON.stringify([5, 6, 8, 9]),
      keywords: JSON.stringify(['joy', 'positivity', 'friendship']),
      stockQuantity: 12,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Green Aquamarine Bracelet',
      slug: 'green-aquamarine-bracelet',
      description: 'A rare variety of aquamarine that promotes emotional healing, compassion, and connection with nature.',
      price: 50.00,
      category: 'Communication',
      chakra: 'Heart',
      element: 'Water',
      hardness: '7.5-8',
      origin: 'Brazil, Madagascar, Pakistan',
      rarity: 'Rare',
      image: '/images/crystals/GREEN AQUAMARINE/GW1.png',
      images: JSON.stringify(['/images/crystals/GREEN AQUAMARINE/GW1.png', '/images/crystals/GREEN AQUAMARINE/GW2.png', '/images/crystals/GREEN AQUAMARINE/GW3.png', '/images/crystals/GREEN AQUAMARINE/GW4.png']),
      properties: JSON.stringify(['Emotional Healing', 'Compassion', 'Communication', 'Empathy']),
      colors: JSON.stringify(['Light Green', 'Blue-Green', 'Teal']),
      zodiacSigns: JSON.stringify(['Pisces', 'Gemini', 'Virgo']),
      birthMonths: JSON.stringify([2, 3, 5, 6, 8, 9]),
      keywords: JSON.stringify(['healing', 'compassion', 'nature']),
      stockQuantity: 8,
      lowStockThreshold: 3,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Howlite Bracelet',
      slug: 'howlite-bracelet',
      description: 'A calming stone that reduces stress and anxiety. Howlite promotes peaceful sleep and patience.',
      price: 25.00,
      category: 'Spiritual Protection',
      chakra: 'Crown',
      element: 'Air',
      hardness: '3.5',
      origin: 'Canada, USA',
      rarity: 'Common',
      image: '/images/crystals/HOWLITE/HW1.png',
      images: JSON.stringify(['/images/crystals/HOWLITE/HW1.png', '/images/crystals/HOWLITE/HW2.png', '/images/crystals/HOWLITE/HW3.png', '/images/crystals/HOWLITE/HW4.png']),
      properties: JSON.stringify(['Calming', 'Stress Relief', 'Patience', 'Sleep', 'Peace']),
      colors: JSON.stringify(['White', 'Cream']),
      zodiacSigns: JSON.stringify(['Gemini', 'Virgo']),
      birthMonths: JSON.stringify([5, 6, 8, 9]),
      keywords: JSON.stringify(['calming', 'stress', 'peace']),
      stockQuantity: 16,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Lapis Lazuli Bracelet',
      slug: 'lapis-lazuli-bracelet',
      description: 'The stone of truth and wisdom. Lapis Lazuli enhances intellectual ability and promotes honest communication.',
      price: 46.00,
      category: 'Communication',
      chakra: 'Throat',
      element: 'Water',
      hardness: '5-5.5',
      origin: 'Afghanistan, Chile, Russia',
      rarity: 'Uncommon',
      image: '/images/crystals/LAPIS LAZULI/LL1.png',
      images: JSON.stringify(['/images/crystals/LAPIS LAZULI/LL1.png', '/images/crystals/LAPIS LAZULI/LL2.png', '/images/crystals/LAPIS LAZULI/LL3.png', '/images/crystals/LAPIS LAZULI/LL4.png']),
      properties: JSON.stringify(['Truth', 'Wisdom', 'Communication', 'Knowledge', 'Intellectual Ability']),
      colors: JSON.stringify(['Deep Blue', 'Blue with Gold']),
      zodiacSigns: JSON.stringify(['Sagittarius', 'Pisces']),
      birthMonths: JSON.stringify([11, 12, 2, 3]),
      keywords: JSON.stringify(['truth', 'wisdom', 'communication']),
      stockQuantity: 11,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Moonstone Bracelet',
      slug: 'moonstone-bracelet',
      description: 'The stone of new beginnings and intuition. Moonstone enhances psychic abilities and promotes emotional balance.',
      price: 36.00,
      category: 'Spiritual Protection',
      chakra: 'Crown',
      element: 'Water',
      hardness: '6-6.5',
      origin: 'India, Sri Lanka, Madagascar',
      rarity: 'Common',
      image: '/images/crystals/MOONSTONE/MO1.png',
      images: JSON.stringify(['/images/crystals/MOONSTONE/MO1.png', '/images/crystals/MOONSTONE/MO2.png', '/images/crystals/MOONSTONE/MO3.png', '/images/crystals/MOONSTONE/MO4.png']),
      properties: JSON.stringify(['Intuition', 'New Beginnings', 'Emotional Balance', 'Psychic Abilities']),
      colors: JSON.stringify(['White', 'Cream', 'Peach', 'Gray']),
      zodiacSigns: JSON.stringify(['Cancer', 'Libra', 'Scorpio']),
      birthMonths: JSON.stringify([6, 7, 9, 10, 11]),
      keywords: JSON.stringify(['intuition', 'beginnings', 'lunar']),
      stockQuantity: 13,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Rhodochrosite Bracelet',
      slug: 'rhodochrosite-bracelet',
      description: 'The stone of the compassionate heart. Rhodochrosite heals emotional wounds and promotes self-love.',
      price: 48.00,
      category: 'Love',
      chakra: 'Heart',
      element: 'Fire',
      hardness: '3.5-4',
      origin: 'Argentina, Peru, USA',
      rarity: 'Rare',
      image: '/images/crystals/RHODOCHROSITE/RW1.png',
      images: JSON.stringify(['/images/crystals/RHODOCHROSITE/RW1.png', '/images/crystals/RHODOCHROSITE/RW2.png', '/images/crystals/RHODOCHROSITE/RW3.png', '/images/crystals/RHODOCHROSITE/RW4.png']),
      properties: JSON.stringify(['Self-Love', 'Emotional Healing', 'Compassion', 'Heart Healing']),
      colors: JSON.stringify(['Pink', 'Rose', 'Red']),
      zodiacSigns: JSON.stringify(['Leo', 'Scorpio']),
      birthMonths: JSON.stringify([7, 8, 10, 11]),
      keywords: JSON.stringify(['self-love', 'healing', 'compassion']),
      stockQuantity: 9,
      lowStockThreshold: 3,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Selenite Bracelet',
      slug: 'selenite-bracelet',
      description: 'A high-vibration stone of purification and spiritual connection. Selenite cleanses energy and promotes mental clarity.',
      price: 38.00,
      category: 'Spiritual Protection',
      chakra: 'Crown',
      element: 'Air',
      hardness: '2',
      origin: 'Morocco, Mexico, USA',
      rarity: 'Common',
      image: '/images/crystals/SELENITE/SL1.png',
      images: JSON.stringify(['/images/crystals/SELENITE/SL1.png', '/images/crystals/SELENITE/SL2.png', '/images/crystals/SELENITE/SL3.png', '/images/crystals/SELENITE/SL4.png']),
      properties: JSON.stringify(['Purification', 'Mental Clarity', 'Spiritual Connection', 'Energy Cleansing']),
      colors: JSON.stringify(['White', 'Clear']),
      zodiacSigns: JSON.stringify(['Taurus', 'Cancer']),
      birthMonths: JSON.stringify([4, 5, 6, 7]),
      keywords: JSON.stringify(['purification', 'clarity', 'spiritual']),
      stockQuantity: 17,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Magnetic Health Bracelet',
      slug: 'magnetic-health-bracelet',
      description: 'A therapeutic bracelet with magnetic properties. Promotes circulation, reduces inflammation, and provides natural pain relief.',
      price: 28.00,
      category: 'Healing',
      chakra: 'Root',
      element: 'Earth',
      hardness: '5-6',
      origin: 'China, USA',
      rarity: 'Common',
      image: '/images/crystals/HEALTH MAGNET BRACELET/HM1.png',
      images: JSON.stringify(['/images/crystals/HEALTH MAGNET BRACELET/HM1.png', '/images/crystals/HEALTH MAGNET BRACELET/HM2.png', '/images/crystals/HEALTH MAGNET BRACELET/HM3.png', '/images/crystals/HEALTH MAGNET BRACELET/HM4.png']),
      properties: JSON.stringify(['Pain Relief', 'Circulation', 'Energy Balance', 'Healing', 'Therapeutic']),
      colors: JSON.stringify(['Metallic Gray', 'Black']),
      zodiacSigns: JSON.stringify(['Virgo', 'Capricorn']),
      birthMonths: JSON.stringify([8, 9, 12, 1]),
      keywords: JSON.stringify(['healing', 'magnetic', 'therapeutic']),
      stockQuantity: 22,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Clear Quartz Master Healer',
      slug: 'clear-quartz-master-healer',
      description: 'The ultimate healing crystal that amplifies energy and brings clarity to all aspects of life.',
      price: 30.00,
      category: 'Healing',
      chakra: 'Crown',
      element: 'Air',
      hardness: '7',
      origin: 'Brazil, Arkansas, Madagascar',
      rarity: 'Common',
      image: '/images/crystals/CLEAR_QUARTZ/CQ1.png',
      images: JSON.stringify(['/images/crystals/CLEAR_QUARTZ/CQ1.png', '/images/crystals/CLEAR_QUARTZ/CQ2.png', '/images/crystals/CLEAR_QUARTZ/CQ3.png', '/images/crystals/CLEAR_QUARTZ/CQ4.png']),
      properties: JSON.stringify(['Amplification', 'Clarity', 'Healing', 'Purification', 'Master Healer']),
      colors: JSON.stringify(['Clear', 'White', 'Transparent']),
      zodiacSigns: JSON.stringify(['All Signs']),
      birthMonths: JSON.stringify([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
      keywords: JSON.stringify(['clarity', 'healing', 'amplification']),
      stockQuantity: 24,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: false,
    },
    {
      name: 'Black Tourmaline Protection',
      slug: 'black-tourmaline-protection',
      description: 'The ultimate protection stone. Black Tourmaline shields against negative energy and electromagnetic radiation.',
      price: 33.00,
      category: 'Protection',
      chakra: 'Root',
      element: 'Earth',
      hardness: '7-7.5',
      origin: 'Brazil, Afghanistan, USA',
      rarity: 'Common',
      image: '/images/crystals/BLACK_TOURMALINE/BT1.png',
      images: JSON.stringify(['/images/crystals/BLACK_TOURMALINE/BT1.png', '/images/crystals/BLACK_TOURMALINE/BT2.png', '/images/crystals/BLACK_TOURMALINE/BT3.png', '/images/crystals/BLACK_TOURMALINE/BT4.png']),
      properties: JSON.stringify(['Protection', 'Grounding', 'EMF Shield', 'Negative Energy Block']),
      colors: JSON.stringify(['Black', 'Dark Gray']),
      zodiacSigns: JSON.stringify(['Capricorn', 'Scorpio']),
      birthMonths: JSON.stringify([10, 11, 12, 1]),
      keywords: JSON.stringify(['protection', 'grounding', 'shield']),
      stockQuantity: 19,
      lowStockThreshold: 5,
      isActive: true,
      isFeatured: false,
    }
  ]

  // Create crystals (upsert to avoid duplicates)
  for (const crystal of crystals) {
    await prisma.crystal.upsert({
      where: { slug: crystal.slug },
      update: crystal,
      create: crystal
    })
  }

  console.log('✅ Created sample crystals')

  // Create a sample admin user (you can sign in with Google OAuth)
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@celestialcrystals.com' },
    update: {},
    create: {
      email: 'admin@celestialcrystals.com',
      firstName: 'Admin',
      lastName: 'User',
      role: 'ADMIN',
      emailVerified: new Date(),
      newsletterSubscribed: true,
      marketingEmails: true,
    }
  })

  console.log('✅ Created admin user')

  // Create some sample reviews
  const tigerEyeCrystal = await prisma.crystal.findFirst({ where: { slug: 'tiger-eye-bracelet' } })
  const aquamarineCrystal = await prisma.crystal.findFirst({ where: { slug: 'aquamarine-bracelet' } })

  if (tigerEyeCrystal) {
    await prisma.review.create({
      data: {
        userId: adminUser.id,
        crystalId: tigerEyeCrystal.id,
        rating: 5,
        title: 'Amazing quality!',
        comment: 'This Tiger Eye bracelet exceeded my expectations. The energy is incredible and it looks beautiful.',
        isVerified: true,
        isApproved: true,
      }
    })
  }

  if (aquamarineCrystal) {
    await prisma.review.create({
      data: {
        userId: adminUser.id,
        crystalId: aquamarineCrystal.id,
        rating: 5,
        title: 'Perfect for clarity work',
        comment: 'I wear this every day during my meditation practice. The calming energy is exactly what I needed.',
        isVerified: true,
        isApproved: true,
      }
    })
  }

  console.log('✅ Created sample reviews')

  console.log('🎉 Database seeded successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
